name: Basic test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a basic test
      run: |
        cd test/basic
        make all
        cd -
